package controller;
/**
 * @author Adhyan Chandhoke
 * Date 11/06/2024
 * This class is a controller for the login screen, handling user authentication and navigation to the redirect page upon successful login.
 */
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 * Controller class for the login screen.
 */
public class LoginController {

    @FXML
    private TextField usernameField; // TextField for entering username

    @FXML
    private PasswordField passwordField; // PasswordField for entering password

    @FXML
    private Label statusLabel; // Label to display status messages

    /**
     * Handles the action when the login button is clicked.
     * @param event The ActionEvent generated by clicking the login button
     */
    @FXML
    private void handleLoginButtonAction(ActionEvent event) {
        String username = usernameField.getText();
        String password = passwordField.getText();

        try (BufferedReader reader = new BufferedReader(new FileReader("users.txt"))) {
            String line;
            boolean found = false;

            // Read each line from the users.txt file
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                // Check if the username and password match
                if (parts[0].equals(username) && parts[1].equals(password)) {
                    found = true;
                    break;
                }
            }

            if (found) {
                loadRedirectPage(); // Redirect to the next page on successful login
            } else {
                statusLabel.setText("Incorrect username or password."); // Display error message
                statusLabel.setStyle("-fx-text-fill: red;"); // Set text color to red
            }
        } catch (IOException e) {
            e.printStackTrace();
            statusLabel.setText("An error occurred while reading the user data."); // Display error message
            statusLabel.setStyle("-fx-text-fill: red;"); // Set text color to red
        }
    }

    /**
     * Loads the redirect page after successful login.
     */
    private void loadRedirectPage() {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/webview/RedirectPage.fxml"));
            Parent redirectRoot = loader.load();
            Stage stage = (Stage) usernameField.getScene().getWindow();
            stage.setScene(new Scene(redirectRoot, 800, 600));
            stage.setTitle("Redirect Page");
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
            statusLabel.setText("Failed to load the redirect page."); // Display error message
            statusLabel.setStyle("-fx-text-fill: red;"); // Set text color to red
        }
    }
}
